[package]
name = "planet-mars"
version = "0.1.0"
edition = "2021"

[dependencies]
# ammonia = "*" done by feed-rs
clap = { version = "*", features = ["derive"] }
env_logger = "*"
feed-rs = "*"
log = "*"
serde = { version = "*", features = ["derive"] }
slug = "*"
tera = "*"
toml = "*"
ureq = { version = "3.0.0-rc5", features = ["brotli", "charset", "gzip", "native-tls"]}
url = "*"

